START TRANSACTION;
INSERT INTO account_types (name_account_type)
VALUES ('administrador'),
    ('usuario'),
    ('moderador');
INSERT INTO item_categories (name_category)
VALUES ('Imoveis'),
    ('Autos e pecas'),
    ('Para casa'),
    ('Celular e Informatica'),
    ('Contratando Serviços'),
    ('Musica e Hobbies'),
    ('Esporte e Lazer'),
    ('Moda e Beleza'),
    ('Bugingangas'),
    ('compra misteriosa');
INSERT INTO item_subcategories (id_category, name_subcategory)
VALUES (1,'Pessoal'),
    (1,'Comercial'),
    (1,'Outros'),
    (2,'Carro'),
    (2,'Moto'),
    (2,'Outros'),
    (3,'Eletrodomesticos'),
    (3,'Utilidades'),
    (3,'Moveis'),
    (3,'Decoracao'),
    (4,'Celulares'),
    (4,'Jogos'),
    (4,'Acessorios'),
    (4,'Computadores'),
    (4,'Outros'),
    (5,'Obras'),
    (5,'Emergenciais'),
    (5,'Outros'),
    (6,'Instrumentos'),
    (6,'Reliquias'),
    (6,'Colecionaveis'),
    (6,'Outros'),
    (7,'Ginastica em casa'),
    (7,'Acessorios'),
    (7,'Outros'),
    (8,'Roupa Masculina'),
    (8,'Roupa Feminina'),
    (8,'Roupa Infantil'),
    (8,'Roupa Pet'),
    (8,'Acessorios'),
    (8,'Outros'),
    (9,'Uteis'),
    (9,'Inuteis'),
    (9,'Zuera'),
    (9,'Decoracao'),
    (9,'Outros');
INSERT INTO users (id_account_type,email_user,login_user,passphrase_user )
VALUES (1,'bruno@gmail.com','bruno_adm','entra21.'),
(1,'denize.f.bassi@gmail.com','denize_adm','entra21.'),
(1,'icaro@gmail.com','icaro_adm','entra21.'),
(1,'jennifer_lye@hotmail.com','jennifer_adm','entra21.'),
(1,'lucas@gmail.com','lucas_adm','entra21.'),
(1,'paula.eduarda@unoesc.edu.br','paula_adm','entra21.'),
(1,'vinicius@gmail.com','vinicius_adm','entra21.'),
(2,'bruno@gmail.com','bruno_usr','entra21.'),
(2,'denize.f.bassi@gmail.com','denize_usr','entra21.'),
(2,'icaro@gmail.com','icaro_usr','entra21.'),
(2,'jennifer_lye@hotmail.com','jennifer_usr','entra21.'),
(2,'lucas@gmail.com','lucas_usr','entra21.'),
(2,'paula.eduarda@unoesc.edu.br','paula_usr','entra21.'),
(2,'vinicius@gmail.com','vinicius_usr','entra21.'),
(3,'bruno@gmail.com','bruno_mod','entra21.'),
(3,'denize.f.bassi@gmail.com','denize_mod','entra21.'),
(3,'icaro@gmail.com','icaro_mod','entra21.'),
(3,'jennifer_lye@hotmail.com','jennifer_mod','entra21.'),
(3,'lucas@gmail.com','lucas_mod','entra21.'),
(3,'paula.eduarda@unoesc.edu.br','paula_mod','entra21.'),
(3,'vinicius@gmail.com','vinicius_mod','entra21.');
    COMMIT;
